services:
  mysql:
    container_name: mysql-container-local
    image: mysql:8.0
    volumes:
      - db-volume:/var/lib/mysql
    env_file:
      - .env.local
    networks:
      - db-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s
  api:
    container_name: api-container-local
    build:
      context: ./api
    env_file:
      - .env.local
    networks:
      - db-network
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      -"8080:8080"

volumes:
  db-volume:

networks:
  db-network:
