services:
  mysql:
    image: mysql:8.0
    container_name: mysql_local_test
    ports:
      - "${DATABASE_PORT}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      TZ: Asia/Seoul
    volumes:
      - mysql-test-volume:/var/lib/mysql
      - ../basedata:/var/lib/mysql-files/basedata

  redis:
    image: redis:alpine
    container_name: redis_dev
    volumes:
      - redis-volume:/data
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    ports:
      - "${REDIS_PORT}:6379"

volumes:
  mysql-test-volume:
  redis-volume: